name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac-arm
            make_command: npm run make:mac-arm
            artifact_name: macos-arm64-build
          - os: macos-latest
            platform: mac-intel
            make_command: npm run make:mac-intel
            artifact_name: macos-x64-build
          - os: windows-latest
            platform: windows
            make_command: npm run make:win
            artifact_name: windows-build
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        env:
          # Always set these environment variables for all platforms
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          MACOS_APPLEID: ${{ secrets.MACOS_APPLEID }}
          MACOS_NOTARIZATION_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
          MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
          # Add this to ensure environment variables are available
          NODE_ENV: production
        run: |
          echo "Building for platform: ${{ matrix.platform }}"
          ${{ matrix.make_command }}
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: out/make/**/*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
      - name: Download macOS ARM64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64-build
          path: ./macos-arm64-build
          
      - name: Download macOS x64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-x64-build
          path: ./macos-x64-build
          
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build  
          path: ./windows-build
          
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./macos-arm64-build/**/*
            ./macos-x64-build/**/*
            ./windows-build/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}